http:
  path: localhost
  port: 8080
database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: homestay_db
  sslmode: disable
storage:
  cloudName: ddhsgiwcv
  apiKey: 584168378272983
  apiSecret: VSBpeP9AKFEzssd3BCvxhc6tyoI
mail:
  from: thoahlgbg2002@gmail.com
  username: 98234847831a02d109f6519a646f72f7
  password: 1bc5f0cd0a27154cf3f6b21d555dee5b